version: "3.5"
services:
  cache:
    image: redis
    container_name: kaavoitus-redis
    command: redis-server
    volumes:
      - cache_kaavoitus_api_data:/data
    ports:
      - "6379:6379"
    restart: on-failure

  kaavoitus-api:
    build:
      context: "."
      dockerfile: Dockerfile.dev
    image: kaavoitus-api
    volumes:
      - .:/kaavoitus-api:rw,cached
      - ./mock-data:/kaavoitus-api/mock-data
      - ./django-db/db.sqlite3:/kaavoitus-api/db/db.sqlite3
    environment:
      - DEBUG=1
      - REDIS_URL=redis://cache
      - ALLOWED_HOSTS=localhost
      - FACTA_DB_MOCK_DATA_DIR=mock-data/
      - USE_JSON_READER=True
      - KAAVAPINO_API_URL=https://kaavapino-testing.ddns.net/v1
    ports:
      - "8000:8000"
    container_name: kaavoitus-api
    depends_on:
      - cache

volumes:
  cache_kaavoitus_api_data:

